import { type NextPage } from "next";
import Head from "next/head";
import { Roboto_Mono } from "@next/font/google";

const robotoMono = Roboto_Mono({ subsets: ["latin"] });

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kapan KKN Selesai?</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-center ${robotoMono.className}`}
      >
        <h2 className="text-xl font-bold uppercase ">Countdown Penarikan</h2>
        <h1 className="text-3xl font-bold uppercase text-[#00A8CC]">
          KKN-PPM UGM
        </h1>
        <h3 className="text-xl font-bold uppercase">Periode 2 Tahun 2021</h3>
        <section className="mt-4 flex text-center">
          <div className="flex flex-col">
            <div className="text-5xl font-extrabold">00</div>
            <div className="mt-2 text-xs font-bold uppercase">Days</div>
          </div>
          <div>&nbsp;</div>
          <div className="flex flex-col">
            <div className="text-5xl font-extrabold">00</div>
            <div className="mt-2 text-xs font-bold uppercase">Hours</div>
          </div>
          <div className="-mt-[2px] text-5xl font-extrabold">:</div>
          <div className="flex flex-col">
            <div className="text-5xl font-extrabold">00</div>
            <div className="mt-2 text-xs font-bold uppercase">Minutes</div>
          </div>
          <div className="-mt-[2px] text-5xl font-extrabold">:</div>
          <div className="flex flex-col">
            <div className="text-5xl font-extrabold">00</div>
            <div className="mt-2 text-xs font-bold uppercase">Seconds</div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
